### ISSUE TITLE
Cant receive report

### ISSUE THREAD

**Issue by shmueldw** [BrokenOpenApp/BrokenOpenApp-Web-Core#78]
Thank you for this project.

I installed BrokenOpenApp-Web-Core on my local server. 
i created new project.
I added to my android project ARCA init code.

```
final ACRAConfiguration config = new ConfigurationBuilder(this)
                .setFormUri("http://192.168.0.101:8080/incomingcrashacra?key=ryb15k3phq9dfq21mweyycn5d2yndy8x1pcpon0691ocjl6ff3shwd3fo")
                .build();
        ACRA.init(this, config);

```

Android logs: 

> Sending report /data/user/0/com.myapp.testarca/app_ACRA-approved/2016-07-18T20:59:58.331+03:00.stacktrace
> Request received by server

But in dashboard i dont see any reports:  Latest 0 issues

Where can be a problem, and how i can to debug server? log files?

Thank you!

**Comment by jarofgreen** [comment]
Logs are in the normal place for your webserver (Apache, etc) and for a Symfony app (app/logs, by default).

Did you set up a Cron task?

```
php app/console brokenopenappcore:process-incoming-crashes --env=prod
```

**Comment by shmueldw** [comment]
I build server with vagrant

```
git clone https://github.com/BrokenOpenApp/BrokenOpenApp-Web-Core.git
cd BrokenOpenApp-Web-Core
vagrant up
vagrant ssh
phpunit -c /vagrant/app/phpunit.xml.dist
```

I need also manually set up a Cron task? 

i run command:
`php app/console brokenopenappcore:process-incoming-crashes --env=prod
`
Terminal log: 

> Done

Try to send crash report again:
A android logs:

> 07-19 08:49:12.074 31681-32173/com.myapp.testarca:acra I/ACRA: Sending report /data/user/0/com.driveway.testarca/app_ACRA-approved/2016-07-19T08:49:11.850+03:00.stacktrace
> 07-19 08:49:13.564 31681-32173/com.myapp.testarca:acra I/ACRA: Request received by server

But still 0 report in dashboard... :/

**Comment by jarofgreen** [comment]
I don't have enough debug info to help with this. You'll have to check the logs and try and work it out. Are you sure your Android device can see the Vagrant box, is networking set up correctly? Can you see the Apache logs (/var/log/apache2 I think) and see if there is an access from your device? Sorry.

**Comment by shmueldw** [comment]
I check /var/log/apache2/access.log 
Server get post request from android:

> 10.0.2.2 - - [19/Jul/2016:07:48:44 +0000] "GET /favicon.ico HTTP/1.1" 200 6819 "http://localhost:8080/project/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
> 10.0.2.2 - - **[19/Jul/2016:07:50:54 +0000] "POST /incomingcrashacra?key=ryb15k3phq9dfq21mweyycn5d2yndy8x1pcpon0691ocjl6ff3shwd3fo HTTP/1.1" 200 232 "-" "Android"**
> 10.0.2.2 - - [19/Jul/2016:07:51:09 +0000] "GET /project/1 HTTP/1.1" 200 1511 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

Maybe ARCA send crash in some different format?  What logs i need to check now? Maybe check something in DB ?

**Comment by shmueldw** [comment]
There are no errors in app/logs/prod.log

**Comment by shmueldw** [comment]
i run again php app/console brokenopenappcore:process-incoming-crashes --env=prod 
It's work me now!! =) thanks.
